spring:
  profiles:
    active: local
    group:
      local: local_server, common, secret
      blue: blue_server, common, secret

---

spring:
  config:
    activate:
      on-profile: local_server
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
server:
  port: 8080
react:
  server:
    protocol: http
    host: localhost
    port: 5173

---

spring:
  config:
    activate:
      on-profile: blue_server
server:
  port: 8080
react:
  server:
    protocol: https
    host: 리액트 서버 배포 주소(ip 또는 도메인)
    port: 5173

---

spring:
  config:
    activate:
      on-profile: common
  servlet:
    multipart:
      max-file-size: 100MB      #업로드 가능한 단일 파일 최대 크기
      max-request-size: 1000MB  #한 번의 요청에서 묶음으로 받을 수 있는 최대 크기
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - profile
              - email
          naver:
            client-name: NAVER
            authorization-grant-type: authorization_code
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


mybatis:
  mapper-locations:
    - /mappers/*.xml
    - /mappers/user/*.xml
    - /mappers/board/*.xml